output_dir: /home/laurits/0407_lifetime_ntuples
temp_dir: /home/laurits/tmp/ntupelized_tmp  # per-file parquets; deleted automatically after merge_and_split
datasets:
  p8_ee_Z_tautau_ecm91:
    input_dir: "/local/joosep/mlpf/cld/v1.2.5_key4hep_2025-05-29/gen/p8_ee_Z_tautau_ecm91/root/"
    file_pattern: "*.root"
    short_name: z
    is_signal: true
    train_frac: 0.70

  p8_ee_Z_qq_ecm91:
    input_dir: "/local/joosep/mlpf/cld/v1.2.5_key4hep_2025-05-29/gen/p8_ee_Z_qq_ecm91/root/"
    file_pattern: "*.root"
    short_name: qq
    is_signal: false
    train_frac: 0.70
weights:
  produce_plots: True
  add_weights: True
  n_files_per_sample: 100000